server:
  port: 8762

spring:
  application:
    name: zuul-service

zuul:
  routes:
    api-a:
#    以/api-a/ 开头的请求都转发给user-service服务
      path: /api-a/**
      serviceId: user-service

eureka:
  client:
    service-url:
#    指定服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/


